### ISSUE TITLE
Présentation incomplète : QGIS et métadonnées

### ISSUE THREAD

**Issue by Guts** [OSGeo-fr/QGIS-user-fr#1]
Le PDF de la présentation de @mfangain semble incomplet (slides vides à partir de la partie 3) : https://github.com/OSGeo-fr/QGIS-user-fr/blob/master/2017/presentations/02_apres_midi/09_Keolis_metadonnees.pdf

Serait-il possible d'avoir la version complète svp ?

**Comment by mfangain** [comment]
Bonjour,

Je n'ai a priori pas les droits pour remettre la bonne version ici.
Je viens d'envoyer une nouvelle version à @yjacolin pour qu'il puisse la corriger.

mfangain

**Comment by yjacolin** [comment]
Hey,

Désolé, je n'ai pas les outils Microsoft donc la génération a du poser problème. Je met à jour le fichier dès réception de la nouvelle version PDF.

Y.
